### ISSUE TITLE
Visiting metrics route throws error

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#43] opened 2021-02-25 13:34 UTC
When visiting the metrics route **directly** in debug mode (`npm start`), the following error is thrown:

![image](https://user-images.githubusercontent.com/49309285/109160797-8c61d480-7776-11eb-9144-6160f835dbf9.png)

**Comment by phpfs** [comment] 2021-02-25 14:44
Resolved with a generic solution. @florian-papsdorf please check if we can improve this further :)

**Closed by phpfs** 2021-02-25 14:44 UTC
Labels: app, bug

**Comment by florian-papsdorf** [comment] 2021-03-02 09:15
It is not a bug. You should not enter a route directly because there is a component which handles the concern. Maybe we can add a hook which will automatically redirect if you enter a non-valid path.
